# Generated by Django 5.2.15 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0124_project_workflow_transition"),
    ]

    operations = [
        migrations.AddField(
            model_name="intake",
            name="template_config",
            field=models.JSONField(default=dict),
        ),
    ]
