# Generated by Django 5.2.15 on 2026-09-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_intake_template_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(default='zh-CN', max_length=255),
        ),
    ]
